In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [5]:
ishvar=pd.read_csv("BuyerRatio (1).csv.csv")
ishvar.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [7]:
# make a dimentional array
ishvar=np.array([[50,142,131,70],[435,1523,1356,750]])


In [8]:
# Chi2 contengency independence test 
# o/p is (Chi2 stats value, p_value, df, expected obsvations)
chi2_contingency(aniket)


(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [9]:
# the p value is 0.6603 is greter than the a therefore the null hypothesis is acceptttted.


In [10]:
data=pd.read_csv("BuyerRatio (1).csv")

In [11]:
data.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [12]:
# make a dimentional array
data=np.array([[50,142,131,70],[435,1523,1356,750]])
data

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [13]:
stat, p, dof, expected=chi2_contingency(data)
alpha=0.05
print("p value is" + str(p))
if p <=alpha:
    print('Dependent(reject H0)')
else:
    print('independent(H0 Hold true)')
    

p value is0.6603094907091882
independent(H0 Hold true)


In [14]:


stat, p, dof, expected = chi2_contingency(data)
  
# interpret p-value
alpha = 0.05 #95% confidence
print("p value is " + str(p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (H0 holds true)')

p value is 0.6603094907091882
Independent (H0 holds true)


In [15]:
stat

1.595945538661058

In [16]:
p

0.6603094907091882

In [17]:
dof

3

In [18]:
##OR

In [21]:
data=np.array([[50,142,131,70],[435,1523,1356,750]])
data

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [23]:
val=stats.chi2_contingency(data)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [25]:
stat

1.595945538661058

In [26]:
p

0.6603094907091882

In [27]:
dof

3

In [29]:
expected

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [31]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(aniket,expected)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

1.5152956451130446

In [32]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [34]:
if chi_square_statestic >= critical_value:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')

Independent (fail to reject H0)


In [35]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

0.6787446296467897

In [37]:
if pvalue <= 0.05:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')

Independent (fail to reject H0)
